version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /srv/sonar/data/:/opt/sonarqube/data
      - /srv/sonar/extensions/:/opt/sonarqube/extensions
      - /srv/sonar/logs/:/opt/sonarqube/logs
      - /srv/sonar/temp/:/opt/sonarqube/temp
    privileged: true
    ports:
      - "9000:9000"
  db:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /srv/pg/:/var/lib/postgresql
      - /srv/pg/data/:/var/lib/postgresql/data
  jenkins:
    container_name: "jenkins"
    build:
      context: .
    environment:
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - /srv/jenkins/certs/:/certs/client:ro
      - /srv/jenkins/data/:/var/jenkins_home
    ports:
      - "9090:8080"
      - "50000:50000"
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker

networks:
  jenkins:
# volumes:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp:
#   postgresql:
#   postgresql_data:
#   jenkins-docker-certs:
#   jenkins-data:
